// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2L1lvnMFLCpsDjljnIT2thGPQ-91XbuI',
    appId: '1:1043023443794:web:156b5ca72918434dd32c8b',
    messagingSenderId: '1043023443794',
    projectId: 'share-bites-31115',
    authDomain: 'share-bites-31115.firebaseapp.com',
    storageBucket: 'share-bites-31115.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHG3mWwJjXTxTMqXQtQiffl9OlVvTIWCc',
    appId: '1:1043023443794:android:727e5c8697a92740d32c8b',
    messagingSenderId: '1043023443794',
    projectId: 'share-bites-31115',
    storageBucket: 'share-bites-31115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdJH-joBfJ74QFonfCsP19szdkK6KAMI',
    appId: '1:1043023443794:ios:dae13f7b8155cc58d32c8b',
    messagingSenderId: '1043023443794',
    projectId: 'share-bites-31115',
    storageBucket: 'share-bites-31115.firebasestorage.app',
    iosBundleId: 'com.example.shareBites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdJH-joBfJ74QFonfCsP19szdkK6KAMI',
    appId: '1:1043023443794:ios:76ed015071bbad0ad32c8b',
    messagingSenderId: '1043023443794',
    projectId: 'share-bites-31115',
    storageBucket: 'share-bites-31115.firebasestorage.app',
    iosBundleId: 'com.sharebites.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2L1lvnMFLCpsDjljnIT2thGPQ-91XbuI',
    appId: '1:1043023443794:web:ed642e20893c640dd32c8b',
    messagingSenderId: '1043023443794',
    projectId: 'share-bites-31115',
    authDomain: 'share-bites-31115.firebaseapp.com',
    storageBucket: 'share-bites-31115.firebasestorage.app',
  );
}
